### ISSUE TITLE
Spec

### ISSUE THREAD

**Issue by hahwul** [hahwul/gee#1]
- [x] write to multiple files and stdout (#2)
- [ ] ~input only stdin / only stderr / all (#3)  `-stdin` `-stdout` `-stdall`~
- [x] append to the given FILEs, do not overwrite (#4)`-append`
- [x] write chunked files (size / line) (#5) `-chunked-line` and ~`-chunked-size`~
```
e.g 
+ limit 10MB and filename=output , input 14MB
- output-1 10MB 
- output-2 4MB 
```
- [x] with line prefix (#6) `-p` and `-prefix`
- [x] with line suffix (#7) `-s` and `-suffix`
- [x] with timestamp (#8) `-with-time`
- [x] with linenumber (#9) `-with-line`
- [x] remove newline(`\r\n`) (#10) `-rmnl`
- [ ] ~to table format(markdown) (#11) `--table-md`~
- [ ] ~to table format(html) (#12) `--able-html`~
- [x] regex (grepping and ungrepping) (#13) `-regex` and `-regexv`
- [x] split in line for prefix/suffix/table-* (#14) `-split`
- [x] format `-format` (`line` `md-table` `html-table` `json`) (#14)
- [x] replace in line`-replace` (#21)
- [x] colorize and uncolor option `-uncolor`
- [x] Distribution files (#15) `-distribute`
```
e.g 
+ with --distribute and files(a.txt / b.txt / c.txt)
input: a-l
a.txt:
a
d
g
j

b.txt:
b
e
h
k

c.txt:
c
f
i
l
```
- [x] Make docs page (#23)

**Comment by hahwul** [comment]
cli lib: `flag`
banner: `no` 
version prefix: `v` (v1.0.0)
